{{- $ev := .Environment.Name }}
helmDefaults:
  tillerNamespace: tillerless
  tillerless: true
  atomic: true
  wait: true
  timeout: 600
  force: true

releases:
  - name: nfs-server-provisioner
    installed: true
    namespace: default
    chart: ./charts/nfs-server-provisioner
    values:
      - values/nfs-server-provisioner.gotmpl
  - name: test-shared-pod-storage
    installed: true
    namespace: default
    chart: ./charts/shared-pod-storage
