apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "shared-pod-storage.fullname" . }}
spec:
  resources:
    requests:
      storage: 100Mi
  storageClassName: nfs
  accessModes:
    - ReadWriteMany